### ISSUE TITLE
Connection closed without error

### ISSUE THREAD

**Issue by Ekstazi** [amphp/websocket#5]
Hi! I used websocket-client to connect to my websocket server. I used default client heartbeart settings with ping/pong enabled. But my server doesn't support ping/pong frames. So instead of triggering error, because the [close_code !== 1000](https://github.com/amphp/websocket/blob/master/src/Rfc6455Client.php#L137) the read function resolves with [null](https://github.com/amphp/websocket/blob/master/src/Rfc6455Client.php#L641). 

I think that client must throw error in that case because not normal close used (close_code !== 1000).

**Comment by trowski** [comment]
I pushed a commit to the `issue-5` branch that changes the behavior on an abnormal close. Please add `"amphp/websocket": "dev-issue-5 as 1-rc2"` to your `composer.json` and run `composer update`.
