### ISSUE TITLE
Custom ping interval being ignored

### ISSUE THREAD

**Issue by ghost** [amphp/websocket#6]
Hello, 

When a new Websocket instance is made, we can pass Options to override some settings. For example:
`new Websocket(new Application(), Options::createServerDefault()->withHeartbeatPeriod(20)->withQueuedPingLimit(10));`

Here in the above, I am overriding the heartbeat period to 20 seconds. The expected behavior from this, as I understand it, is the pings sent to the client should occur every 20 seconds. However, because of the way it's [written](https://github.com/amphp/websocket/blob/master/src/Rfc6455Client.php#L129-L143), they are instead sent every second, thereby ignoring the heartbeat period. By extent, the default period, which is 10 seconds, is also ignored.

The definition of `withHeartbeatPeriod` is: 
> Duration in seconds between pings or other connection activity if the heartbeat is enabled. Default is 10.

The heartbeat is also already enabled by default by passing `Options::createServerDefault()`.

Because the pings are currently sent every second, is the Websocket is not functioning as intended, and thus this is an issue?

**Comment by kelunik** [comment]
The watcher is executed every second, but there's a guard to check the expiry time set in https://github.com/amphp/websocket/blob/master/src/Rfc6455Client.php#L152, so it seems to do the right thing, no?

**Comment by ghost** [comment]
My understanding was the pings were supposed to occur with the interval set (so 20 seconds, or 10 seconds if the default option is used), but the behavior I'm seeing (contrary to the code logic) is it occurs every second. So I'm not sure if this is an issue, or I'm misunderstanding the usage.

**Comment by Sulyvahn194** [comment]
Does this make sense?
