### ISSUE TITLE
Increase token time limit on succesfull pong from client

### ISSUE THREAD

**Issue by wiryonolau** [amphp/websocket#9]
Hi for authentication purpose using token with a time limit. 
Is it reliable to check the pongCount  ? Is pongCount a timestamp ?

```php
$this->metadata->pongCount
```

Example :
If the pong is good then we increase the token time limit. 
If the time limit reach it means the client is disconnect or idle in the normal http
so we can cut off the websocket

**Comment by trowski** [comment]
Sorry for the delay in replying, this flew under my radar.

`pongCount` is the number of pong frames received. `lastHeartbeatAt` is the timestamp that the last ping frame was sent.

Neither of these metrics are great for determining if a websocket is connected. I would recommend building in some sort of status exchange into the protocol you're implementing on the websocket.
